<a href="https://colab.research.google.com/github/Kaini9/Data-Analytics-Training/blob/main/NumPy/Notes/Numpy_Array_shape_and_dim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is numpy?

A Python package called NumPy is mostly used for numerical and scientific computations. It offers arrays and several helpful utilities for swiftly carrying out logical and mathematical calculations. Additionally, it is helpful for random number operations, linear algebra, statistics, and data analysis.
ndarray is the primary object in NumPy. Multidimensional arrays, which typically include components of the same data type, are stored in it.

# Numpy Arrays Vs ordered groups of values
Fixed Size: Once a NumPy array is created, its size remains fixed. If you need to change the size, a new array has to be created.

Same Data Type: The elements in a NumPy array generally have the same data type and occupy the same amount of memory.

Fast Operations: NumPy allows mathematical operations on large amounts of data to be performed quickly with less code.

Widely Used: NumPy arrays are commonly used for data processing in many scientific and data-related Python libraries.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3,4])
print(a)
# this is a one dimenisonal array

[1 2 3 4]


In [2]:
a.shape

(4,)

In [3]:
a.ndim

1

In [4]:
# create a another one dimensional array with 10 elements
b=np.array([1,2,3,4,5,6,7,8,9])

In [5]:
b.shape

(9,)

In [6]:
b.ndim

1

In [7]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape

(2, 3)

In [9]:
# create a 2d array with shape 3*3
np.array([[1,2,3],[1,2,3],[1,2,3]]).ndim

2

In [10]:
# create a another 2d array of shape 4*4
np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [11]:
#create a another 2d array of 2*3
np.array([[1,2,3],[1,2,3]]).ndim

2

In [12]:
#create a 3d array with shape 2*2*2
np.array([[[1,2],[1,2]],[[1,2],[1,2]]]).ndim


3

In [13]:
# create a 3d array with 3*3*3 shape
np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]).ndim

3

# Note
2 means 1d

2*2 means 2d

2*2*2 means 3d

2*2*2*2 means 4d array

In [14]:
# create a array with a shape 3*3*3

In [77]:
import numpy as np

arr = np.arange(27).reshape(3, 3, 3)

print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [15]:
# create a array with a shape 2*1*2

In [79]:
import numpy as np

arr = np.arange(4).reshape(2, 1, 2)

print(arr)

[[[0 1]]

 [[2 3]]]


In [16]:
# dtype
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [17]:
# create with a dtype a int
# dtype
np.array([1,2,3,4],dtype=int)

array([1, 2, 3, 4])

In [18]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
# create a array using a arrange

In [20]:
x = 5          # integer
y = 3.14       # float
z = True       # boolean


In [21]:
# with reshape
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [23]:
# your task create a 45 elements array and then reshape it
# with reshape
np.arange(45).reshape(3,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [24]:
# make a own question and do it

In [80]:
# Create a NumPy array with 12 elements and reshape it into a 3*4 array.

arr = np.arange(12).reshape(3,4)

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [81]:
# Create a NumPy array with 24 elements and reshape it into a 2*3*4 array.

arr = np.arange(24).reshape(2,3,4)

print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
# np.ones and np.zeros
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# np.random
np.random.random((3,4))

array([[0.15108746, 0.101972  , 0.80335404, 0.61788993],
       [0.38667872, 0.55213753, 0.47162763, 0.57173095],
       [0.05370554, 0.24160559, 0.10150825, 0.13064576]])

In [28]:
# np.linspace
np.linspace(-10,10,dtype=int)

array([-10, -10, -10,  -9,  -9,  -8,  -8,  -8,  -7,  -7,  -6,  -6,  -6,
        -5,  -5,  -4,  -4,  -4,  -3,  -3,  -2,  -2,  -2,  -1,  -1,   0,
         0,   1,   1,   1,   2,   2,   3,   3,   3,   4,   4,   5,   5,
         5,   6,   6,   7,   7,   7,   8,   8,   9,   9,  10])

In [29]:
# np.linspace
np.linspace(-5,5,10,dtype=int)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  5])

In [30]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [31]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [32]:
# ndim
a3.ndim

3

In [33]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [35]:
# itemsize
a3.itemsize

8

In [36]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [37]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [38]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [41]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

### Array Functions

In [42]:
a1 = np.random.random((3,3))
a1

array([[0.07817635, 0.76708586, 0.16503569],
       [0.16642209, 0.3214108 , 0.88951322],
       [0.80432143, 0.35717534, 0.40250629]])

In [43]:
a1 = np.round(a1*100)
a1

array([[ 8., 77., 17.],
       [17., 32., 89.],
       [80., 36., 40.]])

In [44]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([10880., 88704., 60520.])

In [45]:
np.max(a1)

np.float64(89.0)

In [46]:
np.min(a2)

np.int64(12)

In [47]:
# mean/median/std/var
np.var(a1)

np.float64(820.8888888888889)

In [48]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.98935825,  0.99952016, -0.96139749],
       [-0.96139749,  0.55142668,  0.86006941],
       [-0.99388865, -0.99177885,  0.74511316]])

In [49]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [50]:
# log and exponents
np.exp(a1)

array([[2.98095799e+03, 2.75851345e+33, 2.41549528e+07],
       [2.41549528e+07, 7.89629602e+13, 4.48961282e+38],
       [5.54062238e+34, 4.31123155e+15, 2.35385267e+17]])

### np.ceil() → Ceiling

Definition: Rounds each number UP to the nearest integer.

Always goes toward +∞, no matter what.

In [51]:
import numpy as np

arr = np.array([1.2, 2.7, -1.5, -2.3])
arr


array([ 1.2,  2.7, -1.5, -2.3])

In [52]:
np.ceil(arr)

array([ 2.,  3., -1., -2.])

### np.floor() → Floor

Definition: Rounds each number DOWN to the nearest integer.

Always goes toward -∞.

In [53]:
np.floor(arr)


array([ 1.,  2., -2., -3.])

### np.round() → Round (to nearest)

Definition: Rounds each number to the nearest integer.

If decimal = 0.5 → rounds to nearest even integer (NumPy behavior).

In [54]:
np.round(arr)


array([ 1.,  3., -2., -2.])

### Indexing and Slicing

In [55]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a2[1,0]

np.int64(4)

In [59]:
a2[1,2]

np.int64(6)

In [60]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
a3[1,0,1]

np.int64(5)

In [62]:
a3[0,1,0]

np.int64(2)

In [63]:
### find the elements 7

In [64]:
# find elements 3

In [65]:
# whats the output
a3[1,1,0]

np.int64(6)

In [66]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Iterating

In [67]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [70]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [71]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


### Reshaping

In [72]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Stacking

In [73]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [76]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])